language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3

install:
    - travis_retry composer install --no-interaction

script:
    - vendor/bin/tester tests -s -p php

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   stage: Code Standard Checker
            php: 7.2
            install:
                - travis_retry composer create-project nette/code-checker temp/code-checker ~2 --no-progress
                # Modify code-checker tasks
                - sed -i -e 's/tabIndentationPhpChecker/yamlIndentationChecker/g' temp/code-checker/src/bootstrap.php
                - sed -i -e 's/\*\.css,\*\.less,\*\.js,\*\.json,\*\.neon/\*\.css,\*\.less,\*\.js,\*\.json/g' temp/code-checker/src/bootstrap.php

            script:
                - php temp/code-checker/src/code-checker.php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
